#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import argparse
import os
import sys


try:
    from httpshell import httpshell
    from httpshell import version
except ImportError:
    sys.path.append(os.path.join(os.path.abspath(os.path.dirname(sys.argv[0]), 'httpshell')))
    from httpshell import httpshell
    from httpshell import version


def parse_command_line():

    parser = argparse.ArgumentParser(
        description="An interactive shell for issuing HTTP commands to a web server or REST API")

    parser.add_argument(
        "url",
        metavar="URL",
        help="url to connect to")

    parser.add_argument(
        "-f", "--format",
        action="store_true",
        default=False,
        dest="auto_format",
        help="Attempt to automatically format known mimetypes (JSON or XML)")

    parser.add_argument(
        "-c", "--no-cookies",
        action="store_true",
        default=False,
        dest="disable_cookies",
        help="Do not respect cookies sent by host")

    parser.add_argument(
        "-n", "--no-headers",
        action="store_false",
        default=True,
        dest="show_headers",
        help="Suppress the display of headers")

    parser.add_argument(
        "-i", "--insecure",
        action="store_true",
        default=False,
        dest="insecure_ssl",
        help="Ignore any untrusted or expired SSL certificates")

    parser.add_argument(
        "--version",
        action="version",
        version="{0} {1}".format("%(prog)s", version.VERSION))

    return parser.parse_args()


def main():
    args = parse_command_line()
    shell = httpshell.HttpShell(args)
    shell.input_loop()


if __name__ == "__main__":
    main()
